FROM node:lts-alpine3.20

WORKDIR /app

# Копируем package.json сначала
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci

# Копируем остальные файлы
COPY . .

# Запускаем dev server с hot reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]