FROM gradle:jdk21-alpine

WORKDIR /app

COPY build.gradle .
COPY gradle.properties .
COPY gradlew .
COPY gradle/ gradle/
COPY src/ src/

# Устанавливаем зависимости
RUN gradle dependencies --no-daemon

# Монтируем исходники через volume для hot reload
VOLUME /app/src

# Запуск с continuous build
CMD ["gradle", "bootRun", "--no-daemon", "--continuous"]
